/**
 * AI review-report domain types (review-reorient Phase 3).
 *
 * The pivot output: the AI acts as a *reviewer* of an external pull request
 * (never a code author). Its work is captured as a {@link ReviewReport} — a
 * human-facing summary plus a list of {@link ReviewFinding}s — and a separate,
 * actionable list of {@link FixSuggestion}s the reviewer can copy out. Both are
 * shown together in the web UI.
 */

import type { AiProviderType } from './integration.js';
import { newFixSuggestionID, newReviewFindingID, newReviewReportID } from './ids.js';
import type { FixSuggestionID, ReviewFindingID, ReviewReportID } from './ids.js';

/** How severe a review finding is (highest first). */
export const ReviewSeverity = {
  Critical: 'CRITICAL',
  Major: 'MAJOR',
  Minor: 'MINOR',
  Nit: 'NIT',
  Info: 'INFO',
} as const;
/** A review finding severity. */
export type ReviewSeverity = (typeof ReviewSeverity)[keyof typeof ReviewSeverity];

/** The overall verdict the review report recommends for the PR. */
export const ReviewVerdict = {
  Approve: 'APPROVE',
  RequestChanges: 'REQUEST_CHANGES',
  Comment: 'COMMENT',
} as const;
/** A recommended review verdict. */
export type ReviewVerdict = (typeof ReviewVerdict)[keyof typeof ReviewVerdict];

/**
 * One problem the AI found in the PR. A finding is a *claim* about a specific
 * place in the diff, so it always carries a `file` (and usually a `line`) — the
 * evidence rule "claim ≠ evidence" applies, but here the claim itself is the
 * reviewable unit.
 */
export interface ReviewFinding {
  /** Unique finding id. */
  readonly id: ReviewFindingID;
  /** Severity band. */
  readonly severity: ReviewSeverity;
  /** Repo-relative file the finding is in. */
  readonly file: string;
  /** 1-based line, when the finding is tied to a single line. */
  readonly line?: number;
  /** What is wrong. */
  readonly message: string;
  /** Optional inline pointer at how to address it (sans code). */
  readonly suggestion?: string;
}

/**
 * An actionable fix proposal. Kept a *separate* list from {@link ReviewFinding}s
 * so the UI can render "what the AI recommends doing" next to "what the AI found"
 * — the two distinct sections the user asked for.
 */
export interface FixSuggestion {
  /** Unique suggestion id. */
  readonly id: FixSuggestionID;
  /** Repo-relative file to change. */
  readonly file: string;
  /** Optional context hunk (the `@@ -.. +.. @@` region) the fix applies to. */
  readonly hunk?: string;
  /** The proposed replacement code. */
  readonly proposed: string;
  /** Why this change is correct / what it fixes. */
  readonly rationale: string;
  /** Stable ordering within the report's suggestion list. */
  readonly orderIndex: number;
}

/**
 * The AI's review of a single pull request. This is terminal *output* — the
 * evidence the reviewer reads — not an intermediate. It is never mutated after
 * creation (only re-generated by a fresh review), so every field is `readonly`.
 */
export interface ReviewReport {
  /** Unique report id. */
  readonly id: ReviewReportID;
  /** The PR URL this report reviews. */
  readonly prUrl: string;
  /** The PR title at review time. */
  readonly prTitle: string;
  /** The AI provider that produced the report. */
  readonly aiProvider: AiProviderType;
  /** The concrete model id used. */
  readonly model: string;
  /** A human-readable executive summary. */
  readonly summary: string;
  /** The recommended verdict. */
  readonly overallVerdict: ReviewVerdict;
  /** All findings, ordered by severity then file. */
  readonly findings: ReviewFinding[];
  /** All fix suggestions, ordered by `orderIndex`. */
  readonly suggestions: FixSuggestion[];
  /** When the report was produced. */
  readonly createdAt: Date;
}

/** Input for {@link createReviewFinding}. */
export type CreateReviewFindingInput = Omit<ReviewFinding, 'id'> &
  Partial<Pick<ReviewFinding, 'id'>>;

/** Build a {@link ReviewFinding}, defaulting `id` to a fresh UUIDv7. */
export function createReviewFinding(input: CreateReviewFindingInput): ReviewFinding {
  return { id: newReviewFindingID(), ...input };
}

/** Input for {@link createFixSuggestion}. */
export type CreateFixSuggestionInput = Omit<FixSuggestion, 'id' | 'orderIndex'> &
  Partial<Pick<FixSuggestion, 'id' | 'orderIndex'>>;

/** Build a {@link FixSuggestion}, defaulting `id` to a fresh UUIDv7 and `orderIndex` to 0. */
export function createFixSuggestion(input: CreateFixSuggestionInput): FixSuggestion {
  return { id: newFixSuggestionID(), orderIndex: 0, ...input };
}

/** Input for {@link createReviewReport}. */
export type CreateReviewReportInput = Omit<
  ReviewReport,
  'id' | 'createdAt' | 'findings' | 'suggestions'
> &
  Partial<Pick<ReviewReport, 'id' | 'createdAt' | 'findings' | 'suggestions'>>;

/**
 * Build a {@link ReviewReport}, defaulting `id` to a fresh UUIDv7, `createdAt` to
 * now, and `findings`/`suggestions` to empty lists.
 */
export function createReviewReport(input: CreateReviewReportInput): ReviewReport {
  return {
    id: newReviewReportID(),
    createdAt: new Date(),
    findings: [],
    suggestions: [],
    ...input,
  };
}
