import { doublePrecision, jsonb, pgTable, text, timestamp } from 'drizzle-orm/pg-core';

/**
 * A/B experiment + run tables (day-09 §2.2).
 *
 * The shadow harness records experiments and per-variant runs here — and *only*
 * here. These tables sit outside the live domain graph precisely so a shadow run
 * can't be mistaken for production state: the harness holds a read-only handle on
 * live tables and writes only to these two. `variant_a`/`variant_b` are full
 * `PipelineVariant` snapshots, so a historical comparison stays reproducible after
 * the variant definitions move on (day-09 §6).
 */

export const abExperiments = pgTable('ab_experiments', {
  // UUIDv7, generated by AbStore on insert.
  id: text('id').primaryKey(),
  variant_a: jsonb('variant_a').notNull(),
  variant_b: jsonb('variant_b').notNull(),
  // The single predefined comparison metric — fixed *before* any run executes;
  // changing it afterward requires a new experiment row (no UPDATE path).
  metric: text('metric').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const abRuns = pgTable('ab_runs', {
  id: text('id').primaryKey(),
  experiment_id: text('experiment_id')
    .notNull()
    .references(() => abExperiments.id),
  // 'A' or 'B' — which side of the experiment this run records.
  variant_id: text('variant_id').notNull(),
  metric_value: doublePrecision('metric_value').notNull(),
  report: jsonb('report').notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});
